### ISSUE TITLE
"There's no main class: 'net.lax1dude.eaglercraft.Client'"

### ISSUE THREAD

**Issue by eeeseses** [PeytonPlayz595/Beta-1.7.3#3]
"> Task :generateJavaScript FAILED
There's no main class: 'net.lax1dude.eaglercraft.Client'"

I Run "gradlew build", You Forgot To Put Client.java In eaglercraft?

**Comment by PeytonPlayz595** [comment]
I changed a bunch of stuff around when updating this a while back and I forgot to update the build.gradlew file, it should be `net.PeytonPlayz585.Client`

**Comment by PeytonPlayz595** [comment]
https://github.com/PeytonPlayz595/Beta-1.7.3/commit/acbb1a3c2c121ec243efb9a41956ad468aab4484
