### ISSUE TITLE
Entity rendering is bugged

### ISSUE THREAD

**Issue by catfoolyou** [PeytonPlayz595/Beta-1.7.3#4]
No idea why this is happening, but entities are not lit properly. Dropped blocks and items work fine. 
From my experience with shaders, the entities might be a different render pass and that might be the problem.

![Screenshot from 2024-09-03 12-31-46](https://github.com/user-attachments/assets/5ff8c192-3b41-413f-8c4e-1128d4ceb109)
![Screenshot from 2024-09-03 12-35-49](https://github.com/user-attachments/assets/c55da3fa-2bb0-42ab-90c0-b53758a55979)

**Comment by PeytonPlayz595** [comment]
@catfoolyou It's because of some changes I made to the lighting to try to help with performance, I reverted the changes but forgot to recompile before pushing the commit, to fix it just recompile the project, this will be fix in the next update.

**Comment by catfoolyou** [comment]
Ah, alr.
