### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by sosaaaaaaaaaaaaaaaaa** [PeytonPlayz595/Beta-1.7.3#5]
Minecraft has crashed!
If this has happened more than once then please copy the text on this screen and publish it in the issues feed of this fork's GitHub repository.

The URL to this fork's GitHub repository is: https://github.com/PeytonPlayz595/Beta-1.7.3

Exception Thrown
----------------------------------
  Line: https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:12571:459
  Type: RangeError
  Desc: Invalid typed array length: 8388608
----------------------------------

RangeError: Invalid typed array length: 8388608
    at new Uint8Array (<anonymous>)
    at AIF (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:1434:190)
    at AOo (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:2396:94)
    at GR (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:7015:112)
    at A23 (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:7010:317)
    at Bs7 (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:2214:209)
    at BdN (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:2215:154)
    at Bbu (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:1584:414)
    at BkT (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:1553:450)
    at BtJ (https://peytonplayz595.github.io/Beta-1.7.3/web/js/app.js:88:63)

minecraft.version = "Beta 1.7.3"
minecraft.author = "PeytonPlayz585"
minecraft.brand = "eaglercraft"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)
webgl.vendor = Google Inc. (Intel)

webgl.anisotropicGlitch = false

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1366
rootElement.clientHeight = 599
window.innerWidth = 1366
window.innerHeight = 599
window.outerWidth = 1366
window.outerHeight = 720
window.devicePixelRatio = 1
window.screen.availWidth = 1366
window.screen.availHeight = 720
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.location.href = https://peytonplayz595.github.io/Beta-1.7.3/web/
window.minecraftServer = undefined

**Comment by PeytonPlayz595** [comment]
Thanks for letting me know! I have identified the cause of this crash and it has since been fixed.
https://github.com/PeytonPlayz595/Beta-1.7.3/commit/059925a075802db0c6b131dc8f33972aede96af1

**Comment by sosaaaaaaaaaaaaaaaaa** [comment]
thanks for fixing!

**Comment by PeytonPlayz595** [comment]
> thanks for fixing!

Yeah uh, there's more to this issue 😭 
It was mipmapping that caused the crash, I thought I fixed it completely but now all in-game textures have no color
