### ISSUE TITLE
World Is completely Pitch Black

### ISSUE THREAD

**Issue by SaiyanGonzalez01** [PeytonPlayz595/Beta-1.7.3#7]
World renders all blocks pitch black.
![Screenshot 2024-10-10 9 35 53 PM](https://github.com/user-attachments/assets/657d8464-169c-406d-bd96-4a8bacfc40cb)

**Comment by SaiyanGonzalez01** [comment]
Sorry for closing it, it fixed itself and then went back to being pitch black, and it is staying like that when I load it up now.

**Comment by catfoolyou** [comment]
Just toggle anaglyph on and off in settings and it goes away

**Comment by SaiyanGonzalez01** [comment]
Tried it and yea it goes away, thanks!
