### ISSUE TITLE
cannot continue past the "click any button to enable sound" screen

### ISSUE THREAD

**Issue by cyiorsomething** [PeytonPlayz595/Beta-1.7.3#8]
barely changed anything
compiled EPK
booted the html to play it

and i cannot continue past the thing
and i didnt even change anything to do with mouse

**Comment by PeytonPlayz595** [comment]
Provide more information, what all did you change in the code or assets and does this happen on the official release?

**Comment by PeytonPlayz595** [comment]
Is there any errors or warnings that appear in the console?

**Comment by cyiorsomething** [comment]
> Is there any errors or warnings that appear in the console?

oh i havent tried checking that
hold on

**Comment by cyiorsomething** [comment]
![image](https://github.com/user-attachments/assets/e1de8f2f-7fb6-40a4-a6b9-5c5df6252e72)


> Is there any errors or warnings that appear in the console?

**Comment by cyiorsomething** [comment]
> Provide more information, what all did you change in the code or assets and does this happen on the official release?

haven't tried that
uhhh
gimme like 10 seconds and i shall say what i changed

**Comment by cyiorsomething** [comment]
> > Provide more information, what all did you change in the code or assets and does this happen on the official release?
> 
> haven't tried that uhhh gimme like 10 seconds and i shall say what i changed

splashes.txt

**Comment by PeytonPlayz595** [comment]
What did you use to compile the EPK?

**Comment by PeytonPlayz595** [comment]
Use the CompileEPK script, Beta still uses eagler's legacy EPK format so any other EPK compilers might not work
